### ISSUE TITLE
Individual Project Selection and Presentation to team 

### ISSUE THREAD

**Issue by pradeepkoneti** [pradeepkoneti/Softwareassurance#1]
@pradeepkoneti @LucasAsato @bgopisetty @stankasala @ReshmaBabuChethan

**Comment by pradeepkoneti** [comment]
- [x] Individual Project Selection

- [x] Presentation to team

**Comment by LucasAsato** [comment]
- [x]  Individual Project Selection

- [x] Presentation to team

**Comment by bgopisetty** [comment]
- [x]  Individual Project Selection

- [x]  Presentation to the team

**Comment by stankasala** [comment]
individual project selection and  Presentation to team is done

**Comment by ReshmaBabuChethan** [comment]
Come up with project proposal draft and presented to the team. 
#1
