### ISSUE TITLE
Open Source Project Analysis

### ISSUE THREAD

**Issue by pradeepkoneti** [pradeepkoneti/Softwareassurance#2]
Analyze the selected open source projects and present your perspective in team meeting.

1. https://github.com/magento/magento2
2. https://github.com/opencart/opencart

If you need more information about the projects, please visit the individual branches for these projects

**Comment by pradeepkoneti** [comment]
- [x] Project Takeaways

- [x] Final decision

**Comment by stankasala** [comment]
- [x] Project Takeaways

- [x]  Final decision

**Comment by bgopisetty** [comment]
- [x] Project Takeaways

- [x] Final Decision

**Comment by LucasAsato** [comment]
- [x] Project Takeaways

- [x] Final Decision

**Comment by ReshmaBabuChethan** [comment]
Completed  Project Takeaways and Final decision
