### ISSUE TITLE
Selecting the Claims from the Open Source Software

### ISSUE THREAD

**Issue by pradeepkoneti** [pradeepkoneti/Softwareassurance#47]
Every team member need to come up with two claims for the Open Source Software

**Comment by LucasAsato** [comment]
1. The system minimizes information interception during check out phase.
2. The system minimizes SQL injection on the logging page.

**Comment by ReshmaBabuChethan** [comment]
1. Login authentication mechanism at Magento software minimizes the unauthorized access.
2. Magento follows industry compliance and privacy policies to minimize the dripping of sensitive data.

**Comment by pradeepkoneti** [comment]
1. Magento is adequately secure against network eavesdropping
2. Magento uses SSL certificates to resist against data loss

**Comment by bgopisetty** [comment]
1. Magento is resilient to malicious code being introduced

**Comment by stankasala** [comment]
1. Magento prevents Unauthorized access to sensitive data
