### ISSUE TITLE
Assurance Claim: Magento minimizes SQL injection on the logging page.

### ISSUE THREAD

**Issue by pradeepkoneti** [pradeepkoneti/Softwareassurance#50]
Need to work on Assurance claim Magento minimizes SQL injection on the logging page.

**Comment by LucasAsato** [comment]
https://lucid.app/invitations/accept/a3ba4703-5216-467c-9712-af7ecc2932b6

**Comment by LucasAsato** [comment]
![Assurance Case_ SQL injection](https://user-images.githubusercontent.com/55063598/95665558-8e0c6200-0b1f-11eb-9e69-ffd61ec9091e.jpeg)
