### ISSUE TITLE
Assurance Claim: Magento software minimizes the  unauthorized access.

### ISSUE THREAD

**Issue by pradeepkoneti** [pradeepkoneti/Softwareassurance#52]
Need to work on Assurance claim Magento software minimizes the admin login unauthorized access.

**Comment by stankasala** [comment]
[https://lucid.app/documents/edit/90b0c792-ea87-4aa7-a7ed-e80d477b934e/0_0?beaconFlowId=B2807709B26081AB#?folder_id=home&browser=icon](url)

**Comment by stankasala** [comment]
![_login Assurance case](https://user-images.githubusercontent.com/70480635/95054549-a875b400-06b7-11eb-8806-d68dc0d45a2c.jpeg)

**Comment by stankasala** [comment]
![_login Assurance case](https://user-images.githubusercontent.com/70480635/95411178-692fa900-08eb-11eb-8ed5-4008123b0c34.png)

**Comment by stankasala** [comment]
[ https://lucid.app/lucidchart/90b0c792-ea87-4aa7-a7ed-e80d477b934e/edit?page=0_0#?folder_id=home&browser=icon](url)

**Comment by stankasala** [comment]
![_login Assurance case (1)](https://user-images.githubusercontent.com/70480635/95633145-ab243080-0a4c-11eb-8291-3742079836b8.jpeg)

**Comment by stankasala** [comment]
![_login Assurance case (2)](https://user-images.githubusercontent.com/70480635/95673132-bcb02a00-0b6b-11eb-802e-a30bb98f4cf3.jpeg)

**Comment by stankasala** [comment]
![_login Assurance case (3)](https://user-images.githubusercontent.com/70480635/95675463-179e4d00-0b7d-11eb-81a1-206af7d4bb71.jpeg)
