### ISSUE TITLE
DFD: Admin Login

### ISSUE THREAD

**Issue by ReshmaBabuChethan** [pradeepkoneti/Softwareassurance#74]

**Comment by stankasala** [comment]
![image](https://user-images.githubusercontent.com/70480635/99014999-8292c900-2519-11eb-8568-7689828764bf.png)

**Comment by stankasala** [comment]
![image](https://user-images.githubusercontent.com/70480635/99200460-127b8180-276b-11eb-9dde-3ccc8c3b294d.png)

**Comment by stankasala** [comment]
![image](https://user-images.githubusercontent.com/70480635/99200487-376ff480-276b-11eb-9342-7195c5affcee.png)
